[package]
name = "id-verifier-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.id-verifier]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.62.0"
default-features = false
